theme: jekyll-theme-slate
plugins:
  - jekyll-relative-links
relative_links:
  enabled: true
  collections: true
include:
  - \src_ps2_settings\ps2Settings.md
  - README.md
title: Tightanium Alloys
show_downloads: true